# Site settings
title: Netlify Post Project
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Test hesabı
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://amazing-raman-864e9e.netlify.app/" # the base hostname & protocol for your site
twitter_username: 
github_username:  developersoftwaretech

# Build settings
markdown: kramdown
