# Site settings
title: Eşya Depolama Ev Eşyası Depolama
email : esyadepolama@hotmail.com
description: > Eşya Depolama hizmetlerimiz ev eşyası depolama, ofis eşyası depolama, parça eşya depolama

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://esyadepolama.netlify.app/" # the base hostname & protocol for your site
twitter_username: 
github_username:  developersoftwaretech

# Build settings
markdown: kramdown
