# Site settings
title: Eşya Depolama Ev Eşyası Depolama
email: your-email@domain.com
description: > 

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://esyadepolama.netlify.app/" # the base hostname & protocol for your site
twitter_username: 
github_username:  developersoftwaretech

# Build settings
markdown: kramdown
